AWSTemplateFormatVersion: 2010-09-09

Description:
  Main template that deploys all infrastructure resources.

Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://se-backend-cfn-templates.s3.eu-west-2.amazonaws.com/infrastructure/vpc.yml
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        VpcCIDR: 10.0.0.0/16
        PublicSubnet1CIDR: 10.0.1.0/24
        PublicSubnet2CIDR: 10.0.2.0/24
        PrivateSubnet1CIDR: 10.0.3.0/24
        PrivateSubnet2CIDR: 10.0.4.0/24

  SecurityGroups:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://se-backend-cfn-templates.s3.eu-west-2.amazonaws.com/infrastructure/sg.yml
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        VPC: !GetAtt VPC.Outputs.VPC

  ALB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://se-backend-cfn-templates.s3.eu-west-2.amazonaws.com/infrastructure/alb.yml
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        VPC: !GetAtt VPC.Outputs.VPC
        Subnets: !GetAtt VPC.Outputs.PublicSubnets
        SecurityGroup: !GetAtt SecurityGroups.Outputs.AppLoadBalancerSecurityGroup

  ECS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://se-backend-cfn-templates.s3.eu-west-2.amazonaws.com/infrastructure/ecs.yml
      Parameters:
        EnvironmentName: !Ref AWS::StackName

  ReportService:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://se-backend-cfn-templates.s3.eu-west-2.amazonaws.com/services/service.yml
      Parameters:
        VPC: !GetAtt VPC.Outputs.VPC
        Cluster: !GetAtt ECS.Outputs.Cluster
        ServiceName: report-service
        DesiredCount: 2
        ContainerImage: 712524022545.dkr.ecr.eu-west-2.amazonaws.com/strawberrye/report-service:latest
        Listener: !GetAtt ALB.Outputs.Listener
        Path: /
        HealthCheckPath: /
        Subnets: !GetAtt VPC.Outputs.PrivateSubnets
        SecurityGroup: !GetAtt SecurityGroups.Outputs.FargateContainerSecurityGroup
