AWSTemplateFormatVersion: 2010-09-09

Description:
  Main template that deploys all infrastructure resources.

Resources:
  Service:
    Type: AWS::ECS::Service
    DependsOn: ListenerRule
    Properties:
      Cluster: !Ref "Cluster"
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 75
      DesiredCount: !Ref "DesiredCount"
      HealthCheckGracePeriodSeconds: 5
      LaunchType: FARGATE
      LoadBalancers:
        - ContainerName: nginx-service
          ContainerPort: 80
          TargetGroupArn: !Ref "TargetGroup"
      NetworkConfiguration:
        AwsvpcConfiguration:
          SecurityGroups: [ !Ref "SecurityGroup" ]
          Subnets: !Ref "Subnets"
#      Role: !Ref "ServiceRole"
      TaskDefinition: !Ref "TaskDefinition"

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
#    DependsOn: TaskExecutionRole
    Properties:
      RequiresCompatibilities:
        - FARGATE
        - EC2
      Family: nginx-service
      NetworkMode: awsvpc
      Cpu: 256
      Memory: 512
      ExecutionRoleArn: !Ref "TaskExecutionRole"
      ContainerDefinitions:
        - Name: nginx-service
          Image: nginx
          PortMappings:
            - ContainerPort: 80
#              HostPort: 80
              Protocol: tcp
          Cpu: 256
          Memory: 512
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /aws/ecs/nginx-service
              awslogs-region: eu-west-2
              awslogs-stream-prefix: ecs

  ServiceLogGroup: # TODO
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/ecs/nginx-service

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 6
      HealthCheckPath: /
      HealthCheckPort: 80
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      Port: 80
      Protocol: HTTP
      TargetType: ip
      UnhealthyThresholdCount: 2
      VpcId: !Ref "VPC"

  ListenerRule:
    Type:
      AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - TargetGroupArn: !Ref "TargetGroup"
          Type: forward
      Conditions:
        - Field: path-pattern
          Values: [ !Ref "Path" ]
      ListenerArn: !Ref "Listener"
      Priority: 1

  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: [ ecs-tasks.amazonaws.com ]
            Action: [ sts:AssumeRole ]
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
