AWSTemplateFormatVersion: 2010-09-09

Description:
  Main template that deploys all infrastructure resources.

Parameters:
  VPC:
    Description: The VPC that the ECS cluster is deployed to
    Type: AWS::EC2::VPC::Id

  Cluster:
    Description: Please provide the ECS Cluster ID that this service should run on
    Type: String

  DesiredCount:
    Description: How many instances of this task should we run across our cluster?
    Type: Number
    Default: 2

  Listener:
    Description: The Application Load Balancer listener to register with
    Type: String

  Path:
    Description: The path to register with the Application Load Balancer
    Type: String
    Default: /

  SecurityGroup:
    Description: Select the Security Group to apply to this service
    Type: AWS::EC2::SecurityGroup::Id

  Subnets:
    Description: Choose which subnets ECS Services should be deployed to this service
    Type: List<AWS::EC2::Subnet::Id>

Resources:
  Service:
    Type: AWS::ECS::Service
    DependsOn: ListenerRule
    Properties:
      Cluster: !Ref "Cluster"
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 75
      DesiredCount: !Ref "DesiredCount"
      HealthCheckGracePeriodSeconds: 5
      LaunchType: FARGATE
      LoadBalancers:
        - ContainerName: nginx-service
          ContainerPort: 80
          TargetGroupArn: !Ref "TargetGroup"
      NetworkConfiguration:
        AwsvpcConfiguration:
          SecurityGroups: [ !Ref "SecurityGroup" ]
          Subnets: !Ref "Subnets"
#      Role: !Ref "ServiceRole"
      TaskDefinition: !Ref "TaskDefinition"

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
#    DependsOn: TaskExecutionRole
    Properties:
      RequiresCompatibilities:
        - FARGATE
        - EC2
      Family: nginx-service
      NetworkMode: awsvpc
      Cpu: 256
      Memory: 512
      ExecutionRoleArn: !Ref "TaskExecutionRole"
      ContainerDefinitions:
        - Name: nginx-service
          Image: nginx
          PortMappings:
            - ContainerPort: 80
#              HostPort: 80
              Protocol: tcp
          Cpu: 256
          Memory: 512
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /aws/ecs/nginx-service
              awslogs-region: eu-west-2
              awslogs-stream-prefix: ecs

  ServiceLogGroup: # TODO
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/ecs/nginx-service

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref "VPC"
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 6
      HealthCheckPath: /
      HealthCheckPort: 80
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      Port: 80
      Protocol: HTTP
      TargetType: ip
      UnhealthyThresholdCount: 2

  ListenerRule:
    Type:
      AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - TargetGroupArn: !Ref "TargetGroup"
          Type: forward
      Conditions:
        - Field: path-pattern
          Values: [ !Ref "Path" ]
      ListenerArn: !Ref "Listener"
      Priority: 1

  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: [ ecs-tasks.amazonaws.com ]
            Action: [ sts:AssumeRole ]
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
