AWSTemplateFormatVersion: 2010-09-09

Description:
  This template deploys a lambda which aggregates data in Reports DynamoDB.

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
