AWSTemplateFormatVersion: 2010-09-09

Description:
  Deploys an Application Load Balancer that exposes our various ECS services.

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

  VPC:
    Type: AWS::EC2::VPC::Id
    Description: Choose which VPC the Application Load Balancer should be deployed to

  Subnets:
    Description: Choose which subnets the Application Load Balancer should be deployed to
    Type: List<AWS::EC2::Subnet::Id>

  SecurityGroup:
    Description: Select the Security Group to apply to the Application Load Balancer
    Type: AWS::EC2::SecurityGroup::Id

Resources:
  # LoadBalancer, Listener, Default TargetGroup
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
#    DependsOn: VPCGatewayAttachment
    Properties:
      IpAddressType: ipv4
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: 30
      Scheme: internet-facing
      SecurityGroups: [ !Ref "SecurityGroup" ]
      Subnets: !Ref "Subnets"
      Type: application

  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    DependsOn: [ LoadBalancer ]
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref "DefaultTargetGroup"
          Type: forward
      LoadBalancerArn: !Ref "LoadBalancer"
      Port: 80
      Protocol: HTTP

  DefaultTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 6
      HealthCheckPath: /
      HealthCheckPort: 80
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      Port: 80
      Protocol: HTTP
      UnhealthyThresholdCount: 2
      VpcId: !Ref "VPC"

Outputs:
  LoadBalancer:
    Description: A reference to the Application Load Balancer
    Value: !Ref "LoadBalancer"

  LoadBalancerUrl:
    Description: The URL of the ALB
    Value: !GetAtt "LoadBalancer.DNSName"

  Listener:
    Description: A reference to a port 80 listener
    Value: !Ref "LoadBalancerListener"
