AWSTemplateFormatVersion: 2010-09-09

Description:
  This template deploys a DynamoDB table for storing device reports.

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String

  TableName:
    Description: A name of the table
    Type: String

Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${EnvironmentName}-${TableName}
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
