AWSTemplateFormatVersion: 2010-09-09

Description:
  This template deploys a Report SNS service.

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String

  TopicName:
    Description: A name for the topic
    Type: String

  TopicDisplayName:
    Description: The display name to use for an Amazon SNS topic with SMS subscriptions
    Type: String

Resources:
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${EnvironmentName}-${TopicName}
      DisplayName: !Sub ${EnvironmentName}-${TopicDisplayName}
      FifoTopic: true
      ContentBasedDeduplication: true

Outputs:
  SNSTopicARN:
    Description: A reference to the SNS Topic ARN
    Value: !Ref SNSTopic
